IMAGE     := simple_ptr_test
ifeq ($(MONOLITHIC),on)
LIBRARIES := ../../../stlplus/source
else
LIBRARIES := ../../strings ../../persistence ../../containers ../../portability
endif
include ../../../makefiles/gcc.mak



