IMAGE     := ini_manager_test
ifeq ($(MONOLITHIC),on)
LIBRARIES := ../../../stlplus/source
else
LIBRARIES := ../../strings ../../persistence ../../subsystems ../../containers ../../portability
endif
include ../../../makefiles/gcc.mak



